---
title: "20BPS1022 Data Cleaning, Imputation and Statistics R code"
output:
  word_document: default
  html_notebook: default
  html_document:
    df_print: paged
  pdf_document: default
---

```{r}
a <- 33 
b <- 200
if (b > a) {
  print("b is greater than a")
}
```

```{r}
a <- 33 
b <- 33
if (b > a) {
  print("b is greater than a")
}else if(a == b){
  print("a and b are equal")
}
```

```{r}
a <- 200
b <- 33
if (b > a) {
  print("b is greater than a")
}else if(a == b){
  print("a and b are equal")
}else{
  print("a is greater than b")
}
```

```{r}
x <- 41
if (x > 10) {
  print("Above ten") 
  if (x > 20) {
    print("and also above 20!") 
  } else {
    print("but not above 20.")
  } 
} else {
  print("below 10.")
}
```

```{r}
a <- 200 
b <- 33 
c <- 500
if (a > b & c > a) {
  print("Both conditions are true")
}
```

```{r}
a <- 200 
b <- 33 
c <- 500
if (a > b | a > c) {
  print("At least one of the conditions are true")
}
```

```{r}


```

```{r}
i<- 1
while(i<6){
  print(i)
  i <- i+1
  if(i==4){
    break
  }
}
```

```{r}
i<- 1
while(i<6){
  i <- i+1
  if(i==3){
    next
  }
  print(i)
}
```

```{r}
dice <- 1 
while (dice <= 6) 
  { if (dice < 6) {
    print("No") 
  } else {
    print("Yes!")
  }
dice <- dice + 1
}
```

```{r}
for(x in 1:10){
  print(x)
}
```

```{r}
fruits <- list("banana","apple","cherry")

for(x in fruits){
  print(x)
}
```


```{r}
dice <- c(1,2,3,4,5,6)
for(x in dice){
  print(x)
}
```

```{r}
fruits <- list("banana","apple","cherry")

for(x in fruits){
  if(x == "cherry"){
    break
  }
  print(x)
}
```


```{r}
fruits <- list("banana","apple","cherry")

for(x in fruits){
  if(x == "apple"){
    next
  }
  print(x)
}
```

```{r}
dice <- 1:6
for (x in dice) { 
  if (x == 6) {
    print(paste("The dice number is", x, "Yes")) 
  } else {
    print(paste("The dice number is", x, "No"))
  }
}
```

```{r}
adj <- list("red", "big", "tasty") 
fruits <- list("apple", "banana", "cherry") 
for (x in adj) { 
  for (y in fruits) {
    print(paste(x, y))
  }
}
```

```{r}
library(dplyr)
```

```{r}
data<-data.frame(x1=1:6, x2=c(1,2,2,3,1,2),x3=c("f","d","j","e","a","d"))
data
arrange(data,x3)
filter(data,x2==2)
mutate(data,x4=x1+x2)
```

```{r}
getwd()
setwd("D:\\SEM5\\LAB\\CSE3505\\LAB_30th_Sept")
getwd()
```

```{r}
data1=read.csv("D:\\SEM5\\LAB\\CSE3505\\LAB_30th_Sept\\Datasample.txt",header=FALSE,sep=" ")
data1
data2=read.csv("D:\\SEM5\\LAB\\CSE3505\\LAB_30th_Sept\\events.csv")
data2
```
```{r}
x=c(1,3,4,5,10)
y=c(2,4,6,8,10)
z=c(10,12,14,16,18)
data3=cbind(x,y,z)
data3
write.csv(data3,file="D:\\SEM5\\LAB\\CSE3505\\LAB_30th_Sept\\practice.csv",row.names=FALSE)
df=data.frame("name"=c("a","b","c"),"language"=c("r","p","j"),age=c(22,25,28))
df
write.table(df,file="D:\\SEM5\\LAB\\CSE3505\\LAB_30th_Sept\\p_text.txt",sep="\t",row.names=TRUE,col.names=NA)
```
```{r}
data(mtcars)
cars=mtcars
mtcars

tail(mtcars)
str(mtcars)
names(mtcars)
rownames(mtcars)
dim(mtcars)
sub1=cbind(mtcars$mpg,mtcars$cyl)
sub2=mtcars[4:8]
sub2
sub3=mtcars[,c(2,6,8)]
sub3
sub4=mtcars[c("mpg","cyl")]
sub4
sub5=subset(mtcars,mpg>18)
sub5

```

```{r}
#table() Function
df=data.frame("Name"=c("abc","cde","def"),"Gender"=c("Male","Female","Male"))
df
table(df)
```

```{r}
x=c(1,2,NA,10,3)
is.na(x)
is.nan(x)
```

```{r}
x=c(1,2,NaN,NA,4)
is.na(x)
is.nan(x)
```

```{r}
#removing missing values
x=c(1,2,NA,4,NA,5)
bad=is.na(x)
x[!bad]
x
```

```{r}
data=data.frame(x1=c(7,2,1,NA,9),x2=c(1,3,1,9,NA),x3=c(NA,8,8,NA,5))
data

complete.cases(data)
data_complete=data[complete.cases(data),]
data_complete

```

```{r}
x=c(1,2,NA,4,NA,5)
y=c("a","b",NA,"d",NA,"f")
good=complete.cases(x,y)
good
x[good]
y[good]
```

```{r}
#airquality dataset
airquality[1:6,]
summary(airquality)
mean(airquality$Ozone,na.rm=TRUE)
good=complete.cases(airquality)
airquality[good,][1:6,]
```

```{r}
#na.omit
x=c(1,24,NA,6,NA,9)
x=na.omit(x)
x
```

```{r}
#data imputation
data=data.frame(marks1=c(NA,22,NA,49,75),marks2=c(81,14,NA,61,12),marks3=c(78.5,19.325,NA,28,48.002))
data

```

```{r}
#impute manually(method 1)
data$marks1[is.na(data$marks1)]=mean(data$marks1,na.rm=TRUE)
data
```

```{r}
library(Hmisc)
```

```{r}
#using Hmisc
impute(data$marks2,median)
```

```{r}
#impute with a specific constant value
impute(data$marks3,2000)
```

```{r}
#impute the entire dataset
all_column_median=apply(data,2,median,na.rm=TRUE)
#imputing median value with NA
for(i in colnames(data))
  data[,i][is.na(data[,i])]=all_column_median[i]
data
```
```{r}
#Module 4
library(MASS)
```
```{r}
painters
painters$School
help(painters)
summary(painters)
```
```{r}
#frequency distribution of qualitative data
school=painters$School
school.freq=table(school)
school.freq
```

```{r}
cbind(school.freq)
```
```{r}
#relative frequency distribution of the painter schools
school.relfreq=school.freq/nrow(painters)
school.relfreq
#enhanced
old=options(digits=1)
school.relfreq
options(old)
cbind(school.relfreq)
options(old)
```
```{r}
#quantitative data
faithful
```
```{r}
head(faithful)
#range of eruption duration
duration=faithful$eruptions
range(duration)
#break the range into non-overlapping sub-intervals
breaks=seq(1.5,5.5, by=0.5)
breaks
#CUT METHOD
duration.cut=cut(duration,breaks,right=FALSE)
#frequency of eruptions in each sub-interval with table function
duration.freq=table(duration.cut)
```
```{r}
#cumulative frequency
duration.cumfreq=cumsum(duration.freq)
duration.cumfreq
```
```{r}
#mean
mean(duration)
#median
median(duration)
#quartiles
quantile(duration)
#percentile
quantile(duration,c(.32,.57,.98))
#range
max(duration)-min(duration)
#interquartile range
IQR(duration)
#variance
var(duration)
#standard deviation
sd(duration)
```
```{r}
library(e1071)
```

```{r}
#central moment
moment(duration,order=3,center=TRUE)
#skewness
skewness(duration)
#kurtosis
kurtosis(duration)
```
```{r}
#visualisation
dat=airquality
plot(dat$Ozone)
plot(dat$Ozone,dat$Wind)
#bar plot
barplot(dat$Ozone,main='Ozone levels',ylab='ozone value')
barplot(dat$Ozone,main='Ozone levels',xlab='ozone value',horiz=TRUE)
#histogram
hist(dat$Solar.R)
#boxplot
boxplot(dat$Ozone)
boxplot(dat[,1:4],main='multiple box plot')


```

```{r}
#lattice graphs
library(lattice)
densityplot(dat$Ozone)
splom(dat[c(1,3,4)])

```
```{r}
#ggplot
library(ggplot2)
ggplot(data = mtcars,
mapping = aes(x=wt,y=mpg))+geom_point()
```

```{r}
ggplot(iris,aes(x=Sepal.Length,y=Petal.Length,col=Species))+geom_point(color="blue")+geom_smooth(color="red")
```



```{r}
ggplot(mtcars,aes(x=gear))+geom_bar()
```
```{r}
#histogram
ggplot(mtcars,aes(x=mpg))+geom_histogram()
#boxplot
ggplot(mtcars,aes(x=as.factor(cyl),y=mpg))+geom_boxplot()
```









